# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - healthcare-rag

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: dockerimagesrohit.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_7F65273A4F5C4AE481E604463BAD56F4 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_C30F4E6E3F5A4E0A8512AF04684FF850 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: dockerimagesrohit.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_7F65273A4F5C4AE481E604463BAD56F4 }}/healthragimage:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    

    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_812FE408882942119F55AF976562A0A8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A1368C2BC06D4F218FB40FF76A896F0E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2B0C041CE2364683BCC6582AAF720BF2 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'healthcare-rag'
          slot-name: 'Production'
          images: 'dockerimagesrohit.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_7F65273A4F5C4AE481E604463BAD56F4 }}/healthragimage:${{ github.sha }}'
          